### ISSUE TITLE
source.cpp.in file placement

### ISSUE THREAD

**Issue by cappelletto** [MecatronicaUSB/uwimageproc#10]
About **source.cpp.in** file placemente:

As cmake imports, modify and later copies the .cpp.in file into the current **build** directory, should it be placed at **scripts** folder or could we just use it in the **source** folder?

I'll see another projects as OpenCV itself to see what they do...

**Comment by cappelletto** [comment]
So far, everybody uses it in the original **src** directory, even rename it as **file.in** and later they copy it into **file.cpp** (yet I still prefer your approach about the **file.cpp.in** name

**Comment by fmoralesh** [comment]
We could use the **src** directory for the **file.cpp** as everybody does, but once the "final" version of the module is achieved.

**Comment by cappelletto** [comment]
Ok, yet if you see some module mature enough, don't hesitate to make the modification for the path

**Comment by fmoralesh** [comment]
CMake now creates **histretch.cpp** in **src** path from the **histretch.cpp.in** file.  Deleted **histretch.cpp** file in **src** from the repository.

**Comment by vgarciac** [comment]
I think we may restore **file.cpp** in **src** directory for development purpose. Is a little bit complicated to work with **.in** file in some IDEs, besides to keep the tracking feature working in the **.cpp** file while compiling locally (without *make*). Also, is easier for external contributors  to read the source code directly from Github before compile the entire module.

**Comment by cappelletto** [comment]
Well, it's doable. As a matter of fact, the configure_file action in cmake
can use any file, it doesn't require .in extension. Yet, make may fail as
it doesn't recognize some cmake directives.

**Comment by vgarciac** [comment]
I already tried to build the module with the **.cpp** file as input for **configure_file()** command, and indeed it worked, *make* detect the *#cmakedefine* flag correctly from **.cpp** file. And that's not all, it detect it even if it is **COMENTED**. For example, if the code contains:
```// #cmakedefine USE_GPU```
It will be transform to
```#define USE_GPU```
if CUDA support is detected, or:
```/* #undef USE_GPU */```
otherwise.

**Comment by vgarciac** [comment]
We found an useful cmake function **add_definitions()** to use instead **configure_file()**. this directive add the desired flag to the COMPILE DEFINITIONS directory property  for the current directory. although it is not shown in the source code the #define line, it works for both CPU-GPU versions. (tested in **videostrip** module). This way is no longer necessary *scripts* files and folder in any module.

**Comment by cappelletto** [comment]
Great, go for it for further implementations

**Comment by cappelletto** [comment]
Sorry to reopen this issue, but there is still a tiny detail. I'll copy the fragment of code here (extracted from videostrip in master branch):

   ```
 int nCuda = - 1;    //<Defines number of detected CUDA devices. By default, -1 acting as error value
    cout << "Built with OpenCV " << CV_VERSION << endl;
#ifdef USE_GPU
    /* CUDA */
    // TODO: read about possible failure at runtime when calling CUDA methods in non-CUDA hardware.
    // CHECK whether it is possible with try-catch pair
    nCuda = cuda::getCudaEnabledDeviceCount();	// we try to detect any existing CUDA device
    cuda::DeviceInfo deviceInfo;

    if (nCuda > 0){
        cout << "CUDA enabled devices detected: " << deviceInfo.name() << endl;
        cuda::setDevice(0);
    }
    else {
#undef USE_GPU
        cout << "No CUDA device detected" << endl;
        cout << "Exiting... use non-GPU version instead" << endl;
    }
#endif
    // TODO: How to operate when multiple CUDA devices are detected?
    // So far, we work with the first detected CUDA device. Maybe, add some CUDA probe mode when called

    cout << "***************************************" << endl;
    cout << "Input: " << InputFile << endl;
```
So, here is my comment: 
When the cmake flag **USE_GPU** is enabled, and no CUDA device detected, couldn't we fall back to the CPU mode by activating the proper flag as in **histretch** module? If so, great, and we could proceed to that into the branch for **videostrip** improvement.

**Comment by fmoralesh** [comment]
Created a branch called **videostriGPUonoff** for this purpose. Previously, even if the cmake recognized CUDA, it was running in the end in CPU.
Reorganized the code in order to properly use the **-cuda=0/1** activation flag if CUDA is found, and fixed declarations on the GPU implementation, creating parallel GPU functions of calcOverlap() and calcBlur().
Now works both CPU and GPU (with CUDA found), along with -cuda flag. Estimation time to strip a 1:15 min. video:
- CPU: 2:45 min.
- GPU: 57 secs.
@vgarciac, keep in mind that your last commit regarding #13 is not implemented in this branch.

**Comment by cappelletto** [comment]
For #13, proceed if possible to a branch merge with master. If current solution for #10 is checked in a couple of systems, you can close the issue. I'll proceed to pull this branch for testing purposes in a non-GPU system.

**Comment by cappelletto** [comment]
As .cpp.in file won't be longer required, I'm closing this topic
