### ISSUE TITLE
Development enviroment setup fot OpenCV and contrib

### ISSUE THREAD

**Issue by cappelletto** [MecatronicaUSB/uwimageproc#12]
Write as wiki, or README or INSTALL, the instructions to setup the development environment for OpenCV 3.2 + CUDA 8.0 and fixed contrib.
Start from the existing **txt** file in the Drive folder

**Comment by fmoralesh** [comment]
Added first version of **INSTALL.md** on main repository folder using existing instructions.
Needs review. Specially OpenCV contrib command, and CMake flags with and without CUDA.

**Comment by cappelletto** [comment]
Perfect, we can work on that as starting point. Thx
