### ISSUE TITLE
Function to calculate the real overlap area between two given frames

### ISSUE THREAD

**Issue by vgarciac** [MecatronicaUSB/uwimageproc#13]
Enhancement for **videostrip** module.
Implemented function that calculates the real overlap by computing the intersection area between transformed and reference frame.

**Comment by cappelletto** [comment]
Being assumed that after the homography reprojection, both images will be projected in the same place, and given that always the intersection produces a convex polygon, your current implementation seems to compute the best overlap estimation.
Some border cases will be pure rotation in the axis perpendicular to the image planes (roll)

**Comment by cappelletto** [comment]
I've tested with several pure translation cases, with reasonable results. However, it still remains to be decided how to proceed with translation + zoom in/out cases. Let me elaborate this case: when you have two images A and B, your function must operate in a commutative way. overlap(A,B) ?= overlap(B,A). If so, it may fail with some specific cases. I can prepare a dataset for testing purposes.

**Comment by vgarciac** [comment]
To solve zoom in/out cases we can use the following function to get the overlap area:
%overlap = A*over* / ( A*0* + A*1* - A*over* )
where A*0* is fixed to *img.width x img.height*, and A*1* can be obtained from *contourArea(vector<Point>)* function.
Do you think this solution will fails in some cases? or won't return the desired value?

**Comment by cappelletto** [comment]
Your proposed equation seems to be fit for general purposes. I'm starting to think this question is more theoretical rather than practical. Perhaps back in lab I'll be able to elaborate the border cases.
I'm closing this issue as you proposed solution will work
