### ISSUE TITLE
GPU compilation time option for improved *histrech*

### ISSUE THREAD

**Issue by cappelletto** [MecatronicaUSB/uwimageproc#8]
Test CPU/GPU compilation time options for histogram stretching for single channel, based on percentile limits.
Already done for CPU

**Comment by fmoralesh** [comment]
- Added GPU implementation of histretch module.
If CUDA is detected, user can decide to use CPU or GPU (parse variable **-cuda=0**, **-cuda=1**). If CUDA is not detected, CPU is used automatically.
- Timing results (both CPU or GPU) can be showed or not using the parse command **-time=1** / **-time=0**.
- Using stretching on all channels and color spaces available in a test image, these are the approximate CPU and GPU execution times:
CPU:  287.716 ms.
GPU:  112.857 ms.
